import type { Metadata } from 'next';
import './globals.css';

// * providers
import AppContextProvider from '@/context/AppContext';

// * components
import Toolbar from '@/components/Toolbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// * types
type LayoutProps = Readonly<{ children: React.ReactNode }>;

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang='en'>
      <body className='h-svh bg-primary-dark text-gray-200'>
        <AppContextProvider>
          <header className='h-16'>
            <div className='i-container flex items-center justify-center h-full'></div>
          </header>
          <Toolbar />
          {children}
        </AppContextProvider>
        <div id='modal-root' />
      </body>
    </html>
  );
}
