import type { Metadata } from 'next';
import './globals.css';

// * react-toastify
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

// * providers
import EditorContextProvider from '@/context/EditorContext';

// * components
import Toolbar from '@/components/Toolbar';
import Tooltip from '@/components/ui/Tooltip';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// * types
type LayoutProps = Readonly<{ children: React.ReactNode }>;

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang='en'>
      <body className='h-svh bg-primary-dark text-gray-200'>
        <EditorContextProvider>
          <header className='h-16'>
            <div className='i-container flex items-center justify-center h-full'></div>
          </header>
          <Toolbar />
          {children}
        </EditorContextProvider>
        <ToastContainer theme='dark' autoClose={3000} toastClassName='!bg-primary-light mr-1' />
        <Tooltip />
        <div id='modal-root' />
      </body>
    </html>
  );
}
